amp: true
architecture: yolov11
batch_size: 16
cache: false
conf_threshold: 0.001
dataset_yaml: data/dataset.yaml
degrees: 0.0
device: '0'
epochs: 100
erasing: 0.4
experiment_name: yolov11-anti-uav
fliplr: 0.5
flipud: 0.0
hp_combination: hp2
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
iou_threshold: 0.6
lr: 0.001
lrf: 0.01
mixup: 0.1
model_name: yolov11s
momentum: 0.9
mosaic: 1.0
optimizer: AdamW
output_dir: runs/train
patience: 50
pretrained: true
save_period: 10
scale: 0.5
seed: 42
translate: 0.1
warmup_epochs: 5.0
weight_decay: 0.0001
workers: 8
